### ISSUE TITLE
Undefined appVersion on Android crashes app

### ISSUE THREAD

**Issue by sbehrends** [APSL/react-native-version-number#10]
While implementing this package in Android I am having an issue while importing the module.

As soon as the module is added to the view I get that appVersion is not an object.

![screenshot 2017-09-19 14 06 36](https://user-images.githubusercontent.com/327827/30605304-f8b1dbf0-9d43-11e7-88d7-9e5bf5256cae.png)

**Comment by quintonn** [comment]
same for me

**Comment by Martin25699** [comment]
same problem

**Comment by sbehrends** [comment]
Tried to fix it myself, but could not do it.
I confirm that the package is proper linked, `react-native link` was executed and the package appears on Android Studio as part of the project.

This code does something really similar. Still cannot make it work :(
https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check/android/src/main/java/io/xogus/reactnative/versioncheck/RNVersionCheckModule.java

**Comment by gomdolkim** [comment]
same problem

**Comment by gomdolkim** [comment]
Actually, I tried to fix it and failed. I wanted to get build number and app version. 
If you still struggle with it, with alternative way you can use react-native-device-info. 
https://github.com/rebeccahughes/react-native-device-info

```
import DeviceInfo from 'react-native-device-info';
DeviceInfo.getVersion()
DeviceInfo.getBuildNumber()
```

**Comment by alvaromb** [comment]
Can you give us a repro example?

**Comment by nitish24p** [comment]
@sbehrends sometimes 
```bash
react-native link
``` 
doesn't link all the dependencies correctly can you check in in you ```MainApplication.java``` you have the following lines

```java

import com.apsl.versionnumber.RNVersionNumberPackage;

  // @NonNull
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    // Add the packages you require here.
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
            Other Packages here,
            new RNVersionNumberPackage() //  <- This line
    );
  }

```

**Comment by nitish24p** [comment]
@alvaromb for the above mentioned issue, it got fixed as react-native link hadn't linked the dependencies correctly. In your README you can give a section for install manually.. I can give a PR if that's ok..

**Comment by alvaromb** [comment]
Sure @nitish24p!

That would be very nice.
