### ISSUE TITLE
Implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by bfanger** [APSL/react-native-version-number#12]
react-native 0.49.3 generates a warning:
> Module RNVersionNumber requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by alvaromb** [comment]
Can you send us a PR @bfanger?

Thanks for reporting 😉

**Comment by jwillingham789** [comment]
`
#import "RNVersionNumber.h"

@implementation RNVersionNumber

- (dispatch_queue_t)methodQueue
{
    return dispatch_get_main_queue();
}

+ (BOOL)requiresMainQueueSetup
{
   return YES;
}

RCT_EXPORT_MODULE()

- (NSDictionary *)constantsToExport
{
    return @{@"appVersion"  : [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"],
             @"buildVersion": [[NSBundle mainBundle] objectForInfoDictionaryKey:(NSString *)kCFBundleVersionKey],
             @"bundleIdentifier"  : [[NSBundle mainBundle] bundleIdentifier]
            };

}

@end
`
