### ISSUE TITLE
Repeatedly performing npm-install fails with EISGIT: Appears to be a git repo or submodule

### ISSUE THREAD

**Issue by sdduursma** [APSL/react-native-version-number#13]
When repeatedly performing `npm install` with a dependency on `react-native-version-number`, npm fails with the error code `EISGIT`.

I have declared a dependency on on `react-native-version-number` in my package.json like so:
```
  ...
  "dependencies": {
    "react-native-version-number": ">=0.2.0",
    ...
  },
  ...
```

Performing `npm install` for the first time succeeds. Performing `npm install` immediately again will fail:
```
$ rm -rf node_modules/
$ npm install
$ <installation succeeds>
$
$ npm install
npm ERR! path <path/to/project/root>/node_modules/react-native-version-number
npm ERR! code EISGIT
npm ERR! git <path/to/project/root>/node_modules/react-native-version-number: Appears to be a git repo or submodule.
npm ERR! git     <path/to/project/root>/node_modules/react-native-version-number
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

When inspecting the installed `react-native-version-number` module in `node_modules`, I found that the module contains a `.git` file.

Any help resolving this failure would be much appreciated. Thanks!

**Comment by alexgvozden** [comment]
seems that project owner needs to remove git repository from the package...

**Comment by kkjdaniel** [comment]
+ 1 - I am also having this issue. As @alexgvozden mentions, the package needs to be updated to remove the `.git` directory from the package. As a temporary fix for @sdduursma , just go into the directory and use `rm -rf .git' this will stop NPM complaining.

**Comment by karltaylor** [comment]
Any plans on this getting fixed?

**Comment by joncursi** [comment]
Bump 😅

**Comment by neo125874** [comment]
@kkjdaniel 's solution got this work!

**Comment by unpokolokko** [comment]
remove it from the node modules performing npm install again.

**Comment by viacheslav-gotsuliak** [comment]
Having same issue

**Comment by mieszko4** [comment]
Please fix it, I have the same issue

**Comment by tnyavdc** [comment]
Bump

**Comment by evanjmg** [comment]
+1

**Comment by geekyDP** [comment]
Having same issue

**Comment by trietlam** [comment]
same issue, and have to manually remove .git directory inside the package

**Comment by brickion** [comment]
+1

**Comment by yutakaA** [comment]
+1

**Comment by IrfyNaz** [comment]
+1

**Comment by goldengecko** [comment]
+1

**Comment by VinceBT** [comment]
+1

**Comment by craig8two** [comment]
+1

**Comment by keech** [comment]
+1

**Comment by adrianboimvaser** [comment]
Is this project dead?

**Comment by duongntb94** [comment]
+ 1

**Comment by Lastin** [comment]
Related issue. https://github.com/APSL/react-native-version-number/issues/20
Fixed in: https://github.com/APSL/react-native-version-number/pull/24

**Comment by MohamedHamedTHL** [comment]
+1

**Comment by alvaromb** [comment]
Sorry! Not dead, just very very busy.

This was merged & solved a while ago.

Thanks for reporting!

**Comment by VinceBT** [comment]
By the way could you also add these files to ignore in the ```.npmignore``` ?

They are useless for the user and it just makes your package heavier.

```
.idea
.eslintrc
.travis.yml
```

**Comment by hadicodes** [comment]
> +1 I am also having this issue. As @alexgvozden mentions, the package needs to be updated to remove the `.git` directory from the package. As a temporary fix for @sdduursma , just go into the directory and use `rm -rf .git` this will stop NPM complaining.

This^ worked for me since I had a custom module (not from) npm installed and it had a .git hidden folder tracking it.  Thanks @kkjdaniel !

**Comment by jose2007kj** [comment]
> rm -rf .git

i did his coomand from my project root folder and i lost my .git file and the branches

**Comment by jo3ran** [comment]
Hey,

I don't want to delete the .git folder in one of the npm packages, since I'm checking out the latest updates for this package from the repo. Thus, I'm not able to install other npm packages, since it keeps complaining, that this particular package has a git repo.

How to proceed? Or: What's the reason of this behavior?

**Comment by jose2007kj** [comment]
@jo3ran try this [link](https://stackoverflow.com/q/27356915/5706413) some imes it might be helpfull

**Comment by tajpouria** [comment]
Ubuntu 18.4
i had same issue fixing by going to given directory and  remove .git  " rm -rf .git " in my case : /home/lenovo/Desktop/native/fun/jobs/node_modules/react-native-safe-area-view

**Comment by zandi2015** [comment]
> +1 I am also having this issue. As @alexgvozden mentions, the package needs to be updated to remove the `.git` directory from the package. As a temporary fix for @sdduursma , just go into the directory and use `rm -rf .git` this will stop NPM complaining.

you can use `rm -rf node_modules/package_name/.git/`  in root terminal....

**Comment by Seb6277** [comment]
Same problem while installing moment package.
`npm install --save moment`

it say `react-native-safe-area-view` is a git repo.

I've remove the `.git` folder and it's works. Are they a reason to put the .git into the package ?

**Comment by arcollector** [comment]
add this to your **package.json** file in the _scripts_ json part

```
"scripts": {
    ...,
    "preinstall": "rm -rf node_modules/react-native-safe-area-view/.git"
  },
```

**Comment by ABibin** [comment]
remove any .git files present in the node_modules folder

In your terminal, from your project folder:
rm -rf node_modules/*/.git

**Comment by davidseek** [comment]
> add this to your **package.json** file in the _scripts_ json part
> 
> ```
> "scripts": {
>     ...,
>     "preinstall": "rm -rf node_modules/react-native-safe-area-view/.git"
>   },
> ```

this works perfectly. thank you

**Comment by nishurishabh** [comment]
kkjdaniel worked for me.

**Comment by cjbt** [comment]
> +1 I am also having this issue. As @alexgvozden mentions, the package needs to be updated to remove the `.git` directory from the package. As a temporary fix for @sdduursma , just go into the directory and use `rm -rf .git` this will stop NPM complaining.

I don't care if this was 2+ years ago. This was the fix for me and I want to say that I love you.

**Comment by BwL1289** [comment]
> > +1 I am also having this issue. As @alexgvozden mentions, the package needs to be updated to remove the `.git` directory from the package. As a temporary fix for @sdduursma , just go into the directory and use `rm -rf .git` this will stop NPM complaining.
> 
> I don't care if this was 2+ years ago. This was the fix for me and I want to say that I love you.

i also love @alexgvozden

**Comment by dirkdirk** [comment]
Try updating NPM to version 6.10.  This is a known issue with NPM v6.9.

https://npm.community/t/npm-6-9-1-is-broken-due-to-git-folder-in-published-tarball/8454/5

**Comment by cherucole** [comment]
> +1 I am also having this issue. As @alexgvozden mentions, the package needs to be updated to remove the `.git` directory from the package. As a temporary fix for @sdduursma , just go into the directory and use `rm -rf .git` this will stop NPM complaining.

This worked like a charm for me

**Comment by prideaux** [comment]
> add this to your **package.json** file in the _scripts_ json part
> 
> ```
> "scripts": {
>     ...,
>     "preinstall": "rm -rf node_modules/react-native-safe-area-view/.git"
>   },
> ```

I also use:

`"postinstall": "rm -rf node_modules/react-native-safe-area-view/.git"`

so that if `npm install` is run then it removes it after installing also.

Therefore I have:

```
  "scripts": {
    ...,
    "preinstall": "rm -rf node_modules/react-native-safe-area-view/.git",
    "postinstall": "rm -rf node_modules/react-native-safe-area-view/.git"
  },
```

**Comment by cjo2** [comment]
Hi there, not sure if this is specific to the zsh console, but I had to adjust the command for it to work for me (two asterisks instead of one).

`rm -rf node_modules/**/.git/`
