### ISSUE TITLE
error with permissions

### ISSUE THREAD

**Issue by dht** [APSL/react-native-version-number#20]
Trace: 
  Error: https://registry.yarnpkg.com/react-native-version-number/-/react-native-version-number-0.3.0.tgz: EACCES: permission denied, open '/Users/guyn/.yarn-cache/npm-react-native-version-number-0.3.0/.git/objects/01/77ba6e129d3bd819d70546e364976e699df8f9'
      at Error (native)

**Comment by AuroreM** [comment]
I've got the same issue :(
@alvaromb Do you have an idea ? :)

**Comment by Lastin** [comment]
For now just run `rm -rf node_modules/react-native-version-number && npm install` if you want to reinstall it all, not need for sudoing.
