### ISSUE TITLE
Error with linking

### ISSUE THREAD

**Issue by Azmeer-crescent** [APSL/react-native-version-number#22]
I had to manually link it to <appRoot>MainApplication.java
```javascript
import com.apsl.versionnumber.RNVersionNumberPackage;  <-- add this
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
	  new RNVersionNumberPackage(),  <-- add this
          new MainReactPackage()
      );
    }
`

**Comment by khalid283** [comment]
If you are linking manually. The above comment for ```MainApplication.java```

```setting.gradle```
```java
include ':react-native-version-number'
project(':react-native-version-number').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-version-number/android')
```
```app/build.gradle```
```java
dependencies {
...
compile project(':react-native-version-number')
...
}
```

**Comment by Azmeer-crescent** [comment]
What I meant was, the normal ```react-native link``` did link the ```settings.gradle``` and ```build.gradle``` properly, but it DID NOT process the ```MainApplication.java``` for some reason.

**Comment by cms24us** [comment]
same issue here, `react-native link` works with android but not with iOS.

```
rnpm-install info Android module react-native-version-number is already linked
rnpm-install info Linking react-native-version-number ios dependency
rnpm-install WARN ERRGROUP Group 'Libraries' does not exist in your Xcode project. We have created it automatically for you.
rnpm-install ERR! Something went wrong while linking. Error: Cannot set property 'DB4148B9FCDC44E99B43AF18' of undefined
Please file an issue here: https://github.com/facebook/react-native/issues
```

not sure if the issue is with react-native-version-number or other kind of issue.

**Comment by efournival** [comment]
Just did `yarn install react-native-version-number` then `react-native link react-native-version-number` and it worked flawlessly:
```
rnpm-install info Linking react-native-version-number ios dependency 
rnpm-install info Platform 'ios' module react-native-version-number has been successfully linked 
rnpm-install info Linking react-native-version-number android dependency 
rnpm-install info Platform 'android' module react-native-version-number has been successfully linked
```

**Comment by cms24us** [comment]
my error is on something else. `react-native-version-number` is linked fine.

**Comment by EleeMosinarY** [comment]
> Just did `yarn install react-native-version-number` then `react-native link react-native-version-number` and it worked flawlessly:
> 
> ```
> rnpm-install info Linking react-native-version-number ios dependency 
> rnpm-install info Platform 'ios' module react-native-version-number has been successfully linked 
> rnpm-install info Linking react-native-version-number android dependency 
> rnpm-install info Platform 'android' module react-native-version-number has been successfully linked
> ```

Did same thing still getting undefined in build number and all 3 in ios
