### ISSUE TITLE
Getting 'undefined' when running on iOS

### ISSUE THREAD

**Issue by berzinsk** [APSL/react-native-version-number#26]
Returns undefined when trying to print out version number on iOS device:

`console.log('versionNumber ', VersionNumber)`
`{appVersion: undefined, buildVersion: undefined, bundleIdentifier: undefined}`

Tested on iOS 11.4 iPhone 8 (simulator and device)

**Comment by neogeno** [comment]
me too

**Comment by jniac** [comment]
@karaoak +1

`undefined` appears when the pod is not installed

via CLI : 
```shell
$ yarn add react-native-version-number
...
$ react-native link
... # some logs eg: rnpm-install info Linking react-native-version-number ios dependency
```
then install pods
```shell
$ cd ios
$ pod install
... # some logs eg: Installing react-native-version-number (0.3.4)
```
then re-build the app from XCode

**Comment by berzinsk** [comment]
Ok, thanks. Would be nice to add this to README file so that others would see it

**Comment by claudioviola** [comment]
I tried to run
`pod install` in iOS folder but I received `[!] No Podfile' found in the project directory.`

I followed the steps of @jniac 

Any helps?

**Comment by dongcp** [comment]
> I tried to run
> `pod install` in iOS folder but I received `[!] No Podfile' found in the project directory.`
> 
> I followed the steps of @jniac
> 
> Any helps?

You have to run `pod init` first

**Comment by claudioviola** [comment]
Thanks @dongcp but now it works without run pod.
Is it possible? I'm only re run the project...
Thanks again

**Comment by franck-nadeau** [comment]
Not sure why, but I had the same problem and the Pod was not inserted in the Podfile.

Here is what I had to add to the Podfile to get this to work:

`pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'`

**Comment by seviltagiyeva** [comment]
Also have this problem , solutions about pod did not help

**Comment by Moreno97** [comment]
Please. follow the installation instructions. We DON'T support pods, so if you want to use the library you have to use `react-native link` or link manually.

**Comment by dale-french** [comment]
`react-native-link` did not work on iOS for me. Worked fine on Android.

Following https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking and linking manually on iOS and then uninstall from simulator, clean and rebuild worked for me.

**Comment by reza-madani** [comment]
> Not sure why, but I had the same problem and the Pod was not inserted in the Podfile.
> 
> Here is what I had to add to the Podfile to get this to work:
> 
> `pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'`

Please add this to Readme.
