### ISSUE TITLE
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-version-number'. Minimum required is 25.0.0

### ISSUE THREAD

**Issue by TylerPin** [APSL/react-native-version-number#28]
Hi I get this error after installing this package.

Changing the SDK build tools revision to 25.0.0 gives me the following error:

`AGPBI: {"kind":"error","text":"Error retrieving parent for item: No resource found that matches the given name \u0027android:TextAppearance.Material.Widget.Button.Borderless.Colored\u0027.","sources":[{"file":"/Users/Pin/Desktop/Workspace-Official/MiFun/ReactNative/EthMall/node_modules/react-native-version-number/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml","position":{"startLine":2}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Error retrieving parent for item: No resource found that matches the given name \u0027android:TextAppearance.Material.Widget.Button.Colored\u0027.","sources":[{"file":"/Users/Pin/Desktop/Workspace-Official/MiFun/ReactNative/EthMall/node_modules/react-native-version-number/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml","position":{"startLine":3}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"No resource found that matches the given name: attr \u0027android:keyboardNavigationCluster\u0027.","sources":[{"file":"/Users/Pin/Desktop/Workspace-Official/MiFun/ReactNative/EthMall/node_modules/react-native-version-number/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml","position":{"startLine":14,"startColumn":20,"startOffset":832,"endColumn":53,"endOffset":865}}],"original":"","tool":"AAPT"}
/Users/Pin/Desktop/Workspace-Official/MiFun/ReactNative/EthMall/node_modules/react-native-version-number/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/Pin/Desktop/Workspace-Official/MiFun/ReactNative/EthMall/node_modules/react-native-version-number/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/Pin/Desktop/Workspace-Official/MiFun/ReactNative/EthMall/node_modules/react-native-version-number/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

:react-native-version-number:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-version-number:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt`

**Comment by MikhailSemichev** [comment]
We are also waiting for this issue solution
the only thing we can do for now is to use
`subprojects {
   afterEvaluate {project ->
       if (project.hasProperty("android")) {
           android {
               compileSdkVersion 26
               buildToolsVersion '26.0.3'
           }
       }
   }
}
`

**Comment by epologee** [comment]
This would be fixed by PR #27, I believe.

**Comment by alvaromb** [comment]
https://github.com/APSL/react-native-version-number/releases/tag/v0.3.6
