### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by tessus** [APSL/react-native-version-number#36]
Just wondering if this project is dead. There are a few PRs open, but nothing has happened so far.

I mean information on how to use it on iOS can't be that hard to merge and should have been added from the start.

**Comment by tessus** [comment]
If the project is dead and/or no longer maintained I'm more than happy to take over. In that case you can transfer the ownership to me.

**Comment by flexbox** [comment]
Seams this project have more features https://github.com/rebeccahughes/react-native-device-info

**Comment by tessus** [comment]
@flexbox yes, I was looking into that project as well. However, it requires GCM on Android and is an overkill, if you need nothing more than the version info.

I'm already in the process of merging the PRs and renaming the classes and module name.
the only PR I can't merge is the Windows code, since I don't have anything to test it with. But I will ask the person who coded it to be a collaborator on my new repo. I think I need someone who has the means to test it and fix issues in case of a problem. When it comes to Windows that's not me.
But as I said, I'm more than happy to have more people having push access to the repo.

**Comment by Sean-Brown** [comment]
thanks @tessus, link to the new repo?

**Comment by tessus** [comment]
The repo is currently empty, since I still have to rename all classes, the module and package name.

I will do this on the weekend, thus everything should be available within the next 2 days. The repo will be available here:
https://github.com/tessus/react-native-version-info

**Comment by tessus** [comment]
The new repo is online: https://github.com/tessus/react-native-version-info

npm package: https://www.npmjs.com/package/react-native-version-info

**Comment by Moreno97** [comment]
Hi @tessus, the project is not dead (since we are using the library in our production apps), but we don't have enough time to maintain all our libraries at the same time.
