### ISSUE TITLE
Type definition does not match JavaScript code

### ISSUE THREAD

**Issue by jens-duttke** [APSL/react-native-version-number#39]
In the JavaScript code there is a default export, the type definition exports the values separately.
This results into an error if you deactivate "allowSyntheticDefaultImports" in the tsconfig.json.

The type definition should looks like:
```
declare module 'react-native-version-number' {
	export default {
		appVersion: string,
		buildVersion: string,
		bundleIdentifier: string
	}
}
```

**Comment by alvaromb** [comment]
https://github.com/APSL/react-native-version-number/releases/tag/v0.3.6
