### ISSUE TITLE
Release app errors

### ISSUE THREAD

**Issue by huytran123** [APSL/react-native-version-number#43]
Hi 
Please use config in "build.gradle" file like this:

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion  safeExtGet('compileSdkVersion', 26)
.......
}
.........

if i don't have buildToolsVersion 23.0.1 or sdk 23 when i release APK, i will receive some errors

Thanks

**Comment by alvaromb** [comment]
https://github.com/APSL/react-native-version-number/releases/tag/v0.3.6
