### ISSUE TITLE
On Android, versions are 1.0 when a variable with a different applicationId or Suffix is specified

### ISSUE THREAD

**Issue by JulienAtanasyan** [APSL/react-native-version-number#6]
If the build is compiled using a flavor/build type with a different applicationId or a suffix is specified, the version returned is 1.0.

`    productFlavors {
        development {
            applicationIdSuffix ".development"
        }
    }
`

**Comment by alvaromb** [comment]
Hi @JulienAtanasyan!

Can you send us a PR for this?

**Comment by cladjules** [comment]
@alvaromb my fault, I realized I was specifying a version number in defaultConfig in app/build.gradle.
I removed it to make sure only the one from the androidManifest is selected.

thanks
